name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - principal  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate snake SVG
        uses: platane/snk@v1.0.0 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: ./snake.svg

